spring:
  datasource:
    url: jdbc:mysql://localhost:3306/projectmanager?autoReconnect=true
    username: root
    password: Baba@228
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update

server:
  port: 8000





